# Generated by Django 3.1.4 on 2021-01-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodelform',
            name='num',
            field=models.CharField(default='japan', max_length=255, verbose_name='番号'),
            preserve_default=False,
        ),
    ]
