# Generated by Django 3.1.4 on 2021-02-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomodelform',
            old_name='userID',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='secondinfomodelform',
            old_name='userID',
            new_name='name',
        ),
    ]
