# Generated by Django 3.1.4 on 2021-02-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210220_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdinfomodelform',
            name='userID',
        ),
    ]
